# []

In [ ]:
help(dict.__init__)

In [ ]:
dict([[1,2],[2,2],[4,3]])

In [ ]:
d = {}
help(type(d))

In [1]:
import torch as tt

In [2]:
i, h =2, 3

X = tt.randint(low=1, high=50, size=(i,1))
H = tt.randint(low=1, high=50, size=(h,1))
X,H

(tensor([[34],
         [13]]),
 tensor([[41],
         [ 6],
         [ 8]]))

In [3]:

w_ir = tt.randint(low=1, high=50, size=(h,i))
b_ir = tt.randint(low=1, high=50, size=(h,1))

w_hr = tt.randint(low=1, high=50, size=(h,h))
b_hr = tt.randint(low=1, high=50, size=(h,1))

w_in = tt.randint(low=1, high=50, size=(h,i))
b_in = tt.randint(low=1, high=50, size=(h,1))

w_hn = tt.randint(low=1, high=50, size=(h,h))
b_hn = tt.randint(low=1, high=50, size=(h,1))

In [5]:
Rt = (tt.mm(w_ir, X) + b_ir) + (tt.mm(w_hr, H) + b_hr) 
assert(Rt.shape == H.shape)
Nt1 = (tt.mm(w_in, X) + b_in) + ((tt.mm(w_hn, H) + b_hn) * Rt)
Nt2 = (tt.mm(w_in, X) + b_in) + (tt.mm(w_hn*Rt, H) + b_hn)
Nt1, Nt2, Nt1-Nt2

(tensor([[3231602],
         [5626635],
         [3606169]]),
 tensor([[3111842],
         [5538409],
         [3577513]]),
 tensor([[119760],
         [ 88226],
         [ 28656]]))

In [6]:
Rt = (tt.mm(w_ir, X) + b_ir) + (tt.mm(w_hr, H)) 
assert(Rt.shape == H.shape)
Nt1 = (tt.mm(w_in, X) + b_in) + ((tt.mm(w_hn, H)) * Rt)
Nt2 = (tt.mm(w_in, X) + b_in) + (tt.mm(w_hn*Rt, H))
Nt1, Nt2, Nt1-Nt2

(tensor([[3081890],
         [5456688],
         [3569643]]),
 tensor([[3081890],
         [5456688],
         [3569643]]),
 tensor([[0],
         [0],
         [0]]))

In [ ]:
a = tt.as_tensor([[[1, 3, 7, 6], [9, 0, 6, 2], [3, 0, 5, 8]], [[1, 0, 1, 0], [2, 1, 0, 3], [0, 0, 6, 1]]])
a.shape, a

In [ ]:
b=tt.argsort(a[:,:,2])
b.shape, b

In [ ]:

sorted_a = a[:,[b[:,i] for i in range(a.shape[0])],:]
sorted_a.shape, sorted_a

In [ ]:

b.shape, b

In [ ]:
b=tt.argsort(a[:,:,2])

sorted_a=tt.stack([a[i,b[i],:] for i in range(a.shape[0])] )
sorted_a

In [ ]:
import torch

In [ ]:
a = torch.as_tensor([[[1, 3, 7, 6], [9, 0, 6, 2], [3, 0, 5, 8]], [[1, 0, 1, 0], [2, 1, 0, 3], [0, 0, 6, 1]]])

b=torch.argsort(a[:,:,2])
sorted_a=torch.stack([a[i,b[i],:] for i in range(a.shape[0])] )
sorted_a

In [ ]:
orted_dim = 1 # sort by rows, preserving each row
sorted_column = 2 # sort rows on value of 3rd column of each row
sorted_a = tt.as_tensor([[[3, 0, 5, 8], [9, 0, 6, 2], [1, 3, 7, 6]], [[2, 1, 0, 3], [1, 0, 1, 0], [0, 0, 6, 1]]])
sorted_a

In [ ]:
# inbuilt 
import os
import sys
import math

# most common
import numpy as np
import matplotlib.pyplot as plt

# pytorch
import torch as tt
import torch.nn as nn
import torch.functional as ff
import torch.distributions as dd
import torch.utils.data as ud

# custom
import known
import known.ktorch as kt

print(f'{sys.version=}\n{np.__version__=}\n{tt.__version__=}\n{known.__version__=}')

In [ ]:
from typing import Any, Callable, Dict, List, Sequence, Set, Tuple, Union, 

In [ ]:
dir(typing)

In [ ]:
help(known.pdate)

In [ ]:
known.ktorch.

In [ ]:
tt.os

In [ ]:
plt.figure(figsize=(12,6))
for px in [ 'first', 'last', 'mid', 'mean' ]:
    a = known.basic.graphfromimage('g1.png', pixel_choice=px)
    plt.plot(a)
plt.show()

In [ ]:
a = known.basic.graphfromimage('g1.png', pixel_choice='last')
plt.plot(a), a.shape, a.ndim, a.dtype#, a

In [ ]:
a = known.basic.graphfromimage('g1.png', pixel_choice='first')
plt.plot(a), a.shape, a.ndim, a.dtype#, a

In [ ]:
a = known.basic.graphfromimage('g1.png', pixel_choice='mid')
plt.plot(a), a.shape, a.ndim, a.dtype#, a

In [ ]:
a = known.basic.graphfromimage('g1.png', pixel_choice='mean')
plt.plot(a), a.shape, a.ndim, a.dtype#, a